### PR TITLE
Add support for Galaxy Tab S6 Lite 2020 LTE (gta4xl)

### PR DESCRIPTION
**Pull request by Fede2782**
This PR aims to bring support for the remaining Exynos 9611 device: Tab S6 Lite 2020 LTE

#20 

Tests: 

- [x] Build and boot on actual Tab S6 Lite 2020 (P615)

Works fine on stock One UI 5.1.1. Encryption disabled, but should correctly work with AOSP encryption format (AES-256)

### CODE REVIEW

**Comment by Royna2544** [comment]
is dlog hook driver a requirement?

**Comment by Fede2782** [comment]
> is dlog hook driver a requirement?

It seems, i found is only used with s6 lite and i would not touch it.

**Comment by Royna2544** [comment]
no
https://github.com/Linux4/samsung_kernel/blob/SM-A515F/fs/dlog_hook.c
remove it

just that, and ill merge

**Comment by Fede2782** [comment]
Done, ready for merge then. In case you'll accept remember to add Tab S6 Lite (p615) in the supported devices list. unfortunately i have not the p610 model so i can guarantee this is only for p615

**Comment by Royna2544** [comment]
> Done, ready for merge then. In case you'll accept remember to add Tab S6 Lite (p615) in the supported devices list. unfortunately i have not the p610 model so i can guarantee this is only for p615

Still a great work adding another device support, thanks.

**Comment by Fede2782** [comment]
Thanks to you also. It has been a pleasure to contribute. Remember to add "Tab S6 Lite" in the repo's description. Have a good day

**Pull request merged**
