### PR TITLE
net: wireless: scsc: Update from P615XXU7FWH7

### PR DESCRIPTION
**Pull request by Fede2782**

### CODE REVIEW

**Comment by Royna2544** [comment]
would be better if you can make it in one pr for trivial stuff...

**Comment by Fede2782** [comment]
> would be better if you can make it in one pr for trivial stuff...



> would be better if you can make it in one pr for trivial stuff...

I made multiple PRs so that you could chose single commits in case you didn't want to update everything. I think this commit could also be merged without many problems since the network card is the same on all the devices, so that people can take advantage of updated driver and have a more uniform and up to date kernel source. In the rare case something doesn't work just revert it.

**Comment by Fede2782** [comment]
I'll close this and then reopen it with a few other minor changes from A515FXXU8HWI1

**Comment by Fede2782** [comment]
@roynatech2544 Hi, I don't know if you have seen but I've made the last pull request instead of this to complete the Grass Kernel source update to the most up to date components from Samsung. Have a good day!

**Pull request closed without merging**
